version: "3"
services:
  mysql:
    container_name: sugar-workflow-mysql
    command: --lower_case_table_names=1
    image: docker.io/mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: activiti
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./src/main/resources/activiti.sql:/docker-entrypoint-initdb.d/data.sql
      - ./_mysql_data:/var/lib/mysql
